/*
-- Query: SELECT * FROM localidad.municipio
LIMIT 0, 1000

-- Date: 2015-05-05 07:55
*/
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (1,'Ahuachapán','0101','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (2,'Apaneca','0102','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (3,'Atiquizaya','0103','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (4,'Concepción de Ataco','0104','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (5,'El Refugio','0105','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (6,'Guaymango','0106','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (7,'Jujutla','0107','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (8,'San Francisco Menéndez','0108','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (9,'San Lorenzo','0109','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (10,'San Pedro Puxtla','0110','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (11,'Tacuba','0111','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (12,'Turín','0112','01');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (13,'Candelaria de la Frontera','0201','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (14,'Coatepeque','0202','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (15,'Chalchuapa','0203','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (16,'El Congo','0204','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (17,'El Porvenir','0205','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (18,'Masahuat','0206','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (19,'Metapán','0207','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (20,'San Antonio Pajonal','0208','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (21,'San Sebastián Salitrillo','0209','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (22,'Santa Ana','0210','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (23,'Santa Rosa Guachipilín','0211','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (24,'Santiago de la Frontera','0212','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (25,'Texistepeque','0213','02');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (26,'Acajutla','0301','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (27,'Armenia','0302','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (28,'Caluco','0303','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (29,'Cuisnahuat','0304','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (30,'Santa Isabel Ishuatán','0305','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (31,'Izalco','0306','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (32,'Juayúa','0307','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (33,'Nahuizalco','0308','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (34,'Nahulingo','0309','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (35,'Salcoatitán','0310','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (36,'San Antonio del Monte','0311','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (37,'San Julián','0312','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (38,'Santa Catarina Masahuat','0313','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (39,'Santo Domingo de Guzmán','0314','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (40,'Sonsonate','0315','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (41,'Sonzacate','0316','03');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (42,'Agua Caliente','0401','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (43,'Arcatao','0402','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (44,'Azacualpa','0403','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (45,'Citalá','0404','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (46,'Comalapa','0405','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (47,'Concepción Quezaltepeque','0406','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (48,'Chalatenango','0407','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (49,'Dulce Nombre de María','0408','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (50,'El Carrizal','0409','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (51,'El Paraíso','0410','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (52,'La Laguna','0411','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (53,'La Palma','0412','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (54,'La Reina','0413','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (55,'Las Vueltas','0414','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (56,'Nombre de Jesús','0415','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (57,'Nueva Concepción','0416','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (58,'Nueva Trinidad','0417','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (59,'Ojos de Agua','0418','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (60,'Potonico','0419','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (61,'San Antonio de la Cruz','0420','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (62,'San Antonio Los Ranchos','0421','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (63,'San Fernando','0422','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (64,'San Francisco Lempa','0423','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (65,'San Francisco Morazán','0424','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (66,'San Ignacio','0425','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (67,'San Isidro Labrador','0426','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (68,'San José Cancasque','0427','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (69,'San José Las Flores ','0428','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (70,'San Luis del Carmen','0429','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (71,'San Miguel de Mercedes','0430','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (72,'San Rafael','0431','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (73,'Santa Rita','0432','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (74,'Tejutla','0433','04');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (75,'Antiguo Cuscatlán','0501','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (76,'Ciudad Arce','0502','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (77,'Colón','0503','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (78,'Comasagua','0504','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (79,'Chiltiupán','0505','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (80,'Huizúcar','0506','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (81,'Jayaque','0507','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (82,'Jicalapa','0508','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (83,'La Libertad','0509','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (84,'Nuevo Cuscatlán','0510','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (85,'Santa Tecla','0511','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (86,'Quezaltepeque','0512','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (87,'Sacacoyo','0513','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (88,'San José Villanueva','0514','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (89,'San Juan Opico','0515','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (90,'San Matías','0516','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (91,'San Pablo Tacachico','0517','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (92,'Tamanique','0518','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (93,'Talnique','0519','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (94,'Teotepeque','0520','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (95,'Tepecoyo','0521','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (96,'Zaragoza','0522','05');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (97,'Aguilares','0601','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (98,'Apopa','0602','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (99,'Ayutuxtepeque','0603','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (100,'Cuscatancingo','0604','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (101,'El Paisnal','0605','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (102,'Guazapa','0606','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (103,'Ilopango','0607','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (104,'Mejicanos','0608','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (105,'Nejapa','0609','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (106,'Panchimalco','0610','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (107,'Rosario de Mora','0611','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (108,'San Marcos','0612','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (109,'San Martín','0613','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (110,'San Salvador','0614','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (111,'Santiago Texacuangos','0615','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (112,'Santo Tomás','0616','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (113,'Soyapango','0617','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (114,'Tonacatepeque','0618','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (115,'Delgado','0619','06');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (116,'Candelaria','0701','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (117,'Cojutepeque','0702','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (118,'El Carmen','0703','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (119,'El Rosario','0704','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (120,'Monte San Juan','0705','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (121,'Oratorio de Concepción','0706','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (122,'San Bartolomé Perulapía','0707','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (123,'San Cristóbal','0708','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (124,'San José Guayabal','0709','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (125,'San Pedro Perulapán','0710','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (126,'San Rafael Cedros','0711','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (127,'San Ramón','0712','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (128,'Santa Cruz Analquito','0713','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (129,'Santa Cruz Michapa','0714','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (130,'Suchitoto','0715','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (131,'Tenancingo','0716','07');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (132,'Cuyultitán','0801','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (133,'El Rosario','0802','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (134,'Jerusalén','0803','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (135,'Mercedes La Ceiba','0804','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (136,'Olocuilta','0805','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (137,'Paraíso de Osorio','0806','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (138,'San Antonio Masahuat','0807','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (139,'San Emigdio','0808','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (140,'San Francisco Chinameca','0809','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (141,'San Juan Nonualco','0810','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (142,'San Juan Talpa','0811','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (143,'San Juan Tepezontes','0812','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (144,'San Luis Talpa','0813','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (145,'San Miguel Tepezontes','0814','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (146,'San Pedro Masahuat','0815','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (147,'San Pedro Nonualco','0816','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (148,'San Rafael Obrajuelo','0817','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (149,'Santa María Ostuma','0818','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (150,'Santiago Nonualco','0819','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (151,'Tapalhuaca','0820','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (152,'Zacatecoluca','0821','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (153,'San Luis La Herradura','0822','08');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (154,'Cinquera','0901','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (155,'Guacotecti','0902','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (156,'Ilobasco','0903','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (157,'Jutiapa','0904','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (158,'San Isidro','0905','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (159,'Sensuntepeque','0906','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (160,'Tejutepeque','0907','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (161,'Victoria','0908','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (162,'Villa Dolores','0909','09');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (163,'Apastepeque','1001','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (164,'Guadalupe','1002','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (165,'San Cayetano Istepeque','1003','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (166,'Santa Clara','1004','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (167,'Santo Domingo','1005','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (168,'San Esteban Catarina','1006','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (169,'San Ildefonso','1007','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (170,'San Lorenzo','1008','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (171,'San Sebastián','1009','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (172,'San Vicente','1010','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (173,'Tecoluca','1011','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (174,'Tepetitán','1012','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (175,'Verapaz','1013','10');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (176,'Alegría','1101','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (177,'Berlín','1102','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (178,'California','1103','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (179,'Concepción Batres','1104','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (180,'El Triunfo','1105','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (181,'Ereguayquín','1106','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (182,'Estanzuelas','1107','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (183,'Jiquilisco','1108','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (184,'Jucuapa','1109','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (185,'Jucuarán','1110','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (186,'Mercedes Umaña','1111','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (187,'Nueva Granada','1112','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (188,'Ozatlán','1113','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (189,'Puerto El Triunfo','1114','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (190,'San Agustín','1115','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (191,'San Buenaventura','1116','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (192,'San Dionisio','1117','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (193,'Santa Elena','1118','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (194,'San Francisco Javier','1119','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (195,'Santa María','1120','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (196,'Santiago de María','1121','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (197,'Tecapán','1122','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (198,'Usulután','1123','11');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (199,'Carolina','1201','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (200,'Ciudad Barrios','1202','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (201,'Comacarán','1203','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (202,'Chapeltique','1204','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (203,'Chinameca','1205','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (204,'Chirilagua','1206','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (205,'El Tránsito','1207','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (206,'Lolotique','1208','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (207,'Moncagua','1209','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (208,'Nueva Guadalupe','1210','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (209,'Nuevo Edén de San Juan','1211','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (210,'Quelepa','1212','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (211,'San Antonio del Mosco','1213','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (212,'San Gerardo','1214','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (213,'San Jorge','1215','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (214,'San Luis de la Reina','1216','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (215,'San Miguel','1217','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (216,'San Rafael Oriente','1218','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (217,'Sesori','1219','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (218,'Uluazapa','1220','12');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (219,'Arambala','1301','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (220,'Cacaopera','1302','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (221,'Corinto','1303','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (222,'Chilanga','1304','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (223,'Delicias de Concepción','1305','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (224,'El Divisadero','1306','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (225,'El Rosario','1307','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (226,'Gualococti','1308','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (227,'Guatajiagua','1309','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (228,'Joateca','1310','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (229,'Jocoaitique','1311','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (230,'Jocoro','1312','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (231,'Lolotiquillo','1313','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (232,'Meanguera','1314','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (233,'Osicala','1315','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (234,'Perquín','1316','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (235,'San Carlos','1317','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (236,'San Fernando','1318','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (237,'San Francisco Gotera','1319','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (238,'San Isidro','1320','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (239,'San Simón','1321','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (240,'Sensembra','1322','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (241,'Sociedad','1323','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (242,'Torola','1324','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (243,'Yamabal','1325','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (244,'Yoloaiquín','1326','13');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (245,'Anamorós','1401','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (246,'Bolívar','1402','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (247,'Concepción de Oriente','1403','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (248,'Conchagua','1404','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (249,'El Carmen','1405','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (250,'El Sauce','1406','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (251,'Intipucá','1407','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (252,'La Unión','1408','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (253,'Lilisque','1409','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (254,'Meanguera del Golfo','1410','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (255,'Nueva Esparta','1411','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (256,'Pasaquina','1412','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (257,'Polorós','1413','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (258,'San Alejo','1414','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (259,'San José','1415','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (260,'Santa Rosa de Lima','1416','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (261,'Yayantique','1417','14');
INSERT INTO `municipio` (`id`,`nombre`,`codigo`,`codigo_depto`) VALUES (262,'Yucuaiquín','1418','14');
